services:

  fastapi_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./deploy:/app/deploy
      - ./create_db.py:/app/create_db.py
      - ./seed_db.py:/app/seed_db.py
      - ./dummy_data.json:/app/dummy_data.json
    ports:
      - "8000:8080"
    env_file:
    - path: ./.env.docker.rc
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1000M"

    
  postgres:
    image: pgvector/pgvector:pg18
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: