"""added extra index

Revision ID: 472d44117e8e
Revises: b1efe4dbd05e
Create Date: 2025-10-18 20:14:40.726028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472d44117e8e'
down_revision: Union[str, Sequence[str], None] = 'b1efe4dbd05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_patient_id'), 'notes', ['patient_id'], unique=False)
    op.drop_constraint(op.f('notes_patient_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'patients', ['patient_id'], ['patient_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_patient_id_fkey'), 'notes', 'patients', ['patient_id'], ['patient_id'])
    op.drop_index(op.f('ix_notes_patient_id'), table_name='notes')
    # ### end Alembic commands ###
